name: Deploy to Play Store

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create local.properties
      run: |
        cd /home/runner/work/Recipe-App
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        echo "API_KEY=${{ secrets.API_KEY }}" >> local.properties
      shell: bash

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build Release APK
      run: ./gradlew assembleRelease
      
    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
        
    - name: Deploy to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: com.aspark.recipeapp
        releaseFiles: app/build/outputs/apk/release/app-release-signed.apk
        track: production
        status: completed
        userFraction: 1
        whatsNewDirectory: whatsnew/
        mappingFile: app/build/outputs/mapping/release/mapping.txt
